
import { GoogleGenAI, Modality, Type } from '@google/genai';
import { FakemonData } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fakemonDetailsSchema = {
  type: Type.OBJECT,
  properties: {
    name: {
      type: Type.STRING,
      description: 'A creative and unique name for the Fakemon, typically one or two words.',
    },
    description: {
      type: Type.STRING,
      description: 'A detailed Pokédex-style entry for the Fakemon, describing its appearance, behavior, and abilities.',
    },
    types: {
      type: Type.ARRAY,
      description: 'An array containing one or two Pokémon types (e.g., ["Fire", "Flying"]).',
      items: { type: Type.STRING },
    },
    abilities: {
        type: Type.ARRAY,
        description: 'An array of 1 to 3 potential abilities for the Fakemon.',
        items: {type: Type.STRING},
    },
    stats: {
      type: Type.OBJECT,
      description: 'Base stats for the Fakemon, with values typically between 1 and 255.',
      properties: {
        hp: { type: Type.INTEGER, description: 'Health Points' },
        attack: { type: Type.INTEGER, description: 'Physical Attack' },
        defense: { type: Type.INTEGER, description: 'Physical Defense' },
        specialAttack: { type: Type.INTEGER, description: 'Special Attack' },
        specialDefense: { type: Type.INTEGER, description: 'Special Defense' },
        speed: { type: Type.INTEGER, description: 'Speed' },
      },
       required: ['hp', 'attack', 'defense', 'specialAttack', 'specialDefense', 'speed'],
    },
  },
  required: ['name', 'description', 'types', 'abilities', 'stats'],
};

export const generateFakemonDetails = async (prompt: string): Promise<FakemonData> => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: `Generate a unique Fakemon based on the following description: "${prompt}"`,
    config: {
      systemInstruction: 'You are a creative Pokémon designer. Generate a unique "Fakemon" based on the user\'s prompt. Provide its details in a structured JSON format according to the provided schema. Ensure the stats are balanced and make sense for the Fakemon described.',
      responseMimeType: 'application/json',
      responseSchema: fakemonDetailsSchema,
    },
  });

  const jsonText = response.text.trim();
  try {
    const parsedJson = JSON.parse(jsonText);
    return parsedJson as FakemonData;
  } catch (e) {
    console.error("Failed to parse JSON response:", jsonText);
    throw new Error("The model returned an invalid data structure.");
  }
};

export const generateFakemonImage = async (prompt: string): Promise<string> => {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [{ text: prompt }],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content.parts ?? []) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }

    throw new Error('No image was generated by the model.');
};
